FROM debian:11-slim

RUN apt update
RUN apt install -y gcc make g++ python3 python3-dev swig curl clang pkg-config
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN export PATH=$PATH:/root/.cargo/bin

COPY ./pjproject /home/pjproject

WORKDIR /home/pjproject

RUN ./configure --enable-shared
RUN make dep
RUN make
RUN make install

WORKDIR /home

COPY ./copy-lib-include.sh copy-lib-include.sh

RUN chmod u+x ./copy-lib-include.sh
RUN bash ./copy-lib-include.sh

WORKDIR /home/pjproject/pjsip-apps/src/swig/python

RUN make
RUN make install

ENV LD_LIBRARY_PATH=/usr/local/lib

WORKDIR /home

CMD ["/bin/bash"]

# docker build -t pjsip -f dockerfiles/Dockerfile.debian . && docker run -it --rm --network net --add-host=host.docker.internal:host-gateway pjsip
# docker build -t pjsip -f dockerfiles/Dockerfile.debian . 
# docker run -it --rm --network net --add-host=host.docker.internal:host-gateway pjsip
# docker run -it --rm --network net --add-host=host.docker.internal:host-gateway -v $(pwd):/home/THE-PJPROJECT pjsip