FROM debian:11-slim

RUN apt update
RUN apt install -y git gcc make g++ python3 python3-dev python3-pip swig

WORKDIR /home
# TODO: add a tag to the repo
RUN pip3 install git+https://github.com/JadKHaddad/THE-PJPROJECT.git --verbose

ENV LD_LIBRARY_PATH=/usr/local/lib

CMD ["/bin/bash"]

# docker build -t pjsip-pip -f dockerfiles/Dockerfile.debian.pip . && docker run -it --rm --network net --add-host=host.docker.internal:host-gateway pjsip-pip
# docker build -t pjsip-pip -f dockerfiles/Dockerfile.debian.pip . 
# docker run -it --rm --network net --add-host=host.docker.internal:host-gateway pjsip-pip
# docker run -it --rm --network net --add-host=host.docker.internal:host-gateway -v $(pwd):/home/THE-PJPROJECT pjsip-pip