FROM debian:11-slim

RUN apt update
RUN apt install -y git gcc make g++ python3 python3-dev python3-pip swig

WORKDIR /home
RUN pip3 install git+https://github.com/JadKHaddad/THE-PJPROJECT.git --verbose

ENV LD_LIBRARY_PATH /usr/local/lib

COPY . /home/THE_PJPROJECT

WORKDIR /home/THE_PJPROJECT

CMD ["/bin/bash"]

# docker build -t pjsip-pip -f dockerfiles/Dockerfile.debian.pip . && docker run -it --rm --network net --add-host=host.docker.internal:host-gateway pjsip-pip