name: PJ

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt update
    - name: install dep
      run: sudo apt install -y git gcc make g++ python3 python3-dev swig curl clang
    - name: install rust
      run: |
        sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
        export PATH=$PATH:/root/.cargo/bin
    - name: build pjsip
      working-directory: ./pjproject
      run: |
        sudo ./configure --enable-shared
        sudo make dep
        sudo make
        sudo make install
    - name: build python module
      working-directory: ./pjproject/pjsip-apps/src/swig/python
      run: |
        sudo make
        sudo make install
    - name: export env
      run: export LD_LIBRARY_PATH=/usr/local/lib
